/**
 * coverwise — Combinatorial test design API.
 *
 * Not just a generation tool — a test design engine.
 * JSON-complete, stateless, decomposable.
 */

// --- Public Types ---

export interface ParameterValue {
  value: string;
  invalid?: boolean;
  aliases?: string[];
}

export interface Parameter {
  name: string;
  values: (string | ParameterValue)[];
}

export interface SubModel {
  parameters: string[];
  strength: number;
}

export interface WeightConfig {
  [parameterName: string]: {
    [value: string]: number;
  };
}

export interface GenerateInput {
  parameters: Parameter[];
  constraints?: string[];
  strength?: number;
  seed?: number;
  weights?: WeightConfig;
  seeds?: TestCase[];
  maxTests?: number;
  subModels?: SubModel[];
}

/**
 * A test case as a readable key-value map.
 * e.g. { os: "win", browser: "chrome", arch: "x64" }
 */
export interface TestCase {
  [parameterName: string]: string | number | boolean;
}

/**
 * A human-readable uncovered tuple with context.
 */
export interface UncoveredTuple {
  /** e.g. ["os=win", "browser=safari"] */
  tuple: string[];
  /** Parameter names involved. */
  params: string[];
  /** Why this tuple is uncovered. */
  reason: string;
  /** Human-readable display string. */
  display: string;
}

/**
 * Statistics for evaluation and comparison.
 */
export interface GenerateStats {
  totalTuples: number;
  coveredTuples: number;
  testCount: number;
}

export interface GenerateResult {
  tests: TestCase[];
  negativeTests?: TestCase[];
  coverage: number;
  /** Uncovered tuples with context. Empty when coverage is 1.0. */
  uncovered: UncoveredTuple[];
  /** Statistics for evaluation and comparison. */
  stats: GenerateStats;
  /** Actionable suggestions with proposed test cases. */
  suggestions: Array<{ description: string; testCase: Record<string, string> }>;
  /** Warnings (e.g. performance degradation). */
  warnings: string[];
  /** Strength used for generation. */
  strength: number;
  /** Equivalence class coverage (present when parameters have equivalence classes). */
  classCoverage?: {
    totalClassTuples: number;
    coveredClassTuples: number;
    classCoverageRatio: number;
  };
}

export interface CoverageReport {
  totalTuples: number;
  coveredTuples: number;
  coverageRatio: number;
  /** Every uncovered tuple with context. */
  uncovered: UncoveredTuple[];
}

export interface ExtendInput extends GenerateInput {
  /** How to handle existing tests. */
  mode?: 'strict';
}

export interface ModelStats {
  parameterCount: number;
  totalValues: number;
  strength: number;
  totalTuples: number;
  estimatedTests: number;
  subModelCount: number;
  constraintCount: number;
  parameters: Array<{
    name: string;
    valueCount: number;
    invalidCount: number;
  }>;
}

/**
 * Structured error with context.
 * Errors are always explanatory — never just a code.
 */
export interface CoverwiseError {
  code: 'CONSTRAINT_ERROR' | 'INSUFFICIENT_COVERAGE' | 'INVALID_INPUT' | 'TUPLE_EXPLOSION';
  message: string;
  detail?: string;
}

// --- WASM Module Loading ---

interface WasmModule {
  generate(input: unknown): unknown;
  analyzeCoverage(params: unknown, tests: unknown, strength: number): unknown;
  extendTests(existing: unknown, input: unknown): unknown;
  estimateModel(input: unknown): unknown;
}

let wasmModule: WasmModule | null = null;
let initPromise: Promise<WasmModule> | null = null;

/**
 * Initialize the WASM module. Must be called before using any API function.
 * Safe to call multiple times — only loads once.
 *
 * @example
 * await init();
 * const result = generate({ parameters: [...] });
 */
export async function init(): Promise<void> {
  if (wasmModule) {
    return;
  }
  if (!initPromise) {
    initPromise = (async () => {
      // @ts-expect-error — WASM module is generated by `make wasm`, not present at type-check time.
      const createModule = await import('../dist/coverwise.js');
      const mod = await createModule.default();
      return mod as WasmModule;
    })();
  }
  wasmModule = await initPromise;
}

function getModule(): WasmModule {
  if (!wasmModule) {
    throw new Error('coverwise WASM module not initialized. Call await init() first.');
  }
  return wasmModule;
}

// --- Result Checking ---

function checkResult<T>(result: unknown): T {
  const r = result as Record<string, unknown>;
  if (r && r.error === true) {
    const err: CoverwiseError = {
      code: (r.code as CoverwiseError['code']) ?? 'INVALID_INPUT',
      message: (r.message as string) ?? 'Unknown error',
    };
    throw err;
  }
  return result as T;
}

// --- Core API ---

/**
 * Generate a covering array. One function, sensible defaults.
 *
 * @example
 * const result = generate({
 *   parameters: [
 *     { name: "os", values: ["win", "mac", "linux"] },
 *     { name: "browser", values: ["chrome", "firefox", "safari"] },
 *   ],
 * });
 * // result.tests: [{ os: "win", browser: "chrome" }, ...]
 * // result.coverage: 1.0
 */
export function generate(input: GenerateInput): GenerateResult {
  const mod = getModule();
  const result = checkResult<GenerateResult>(mod.generate(input));
  return result;
}

/**
 * Analyze t-wise coverage of an existing test suite.
 * Use this to check coverage of manually written tests.
 *
 * @example
 * const report = analyzeCoverage(
 *   [{ name: "os", values: ["win", "mac"] }, ...],
 *   [{ os: "win", browser: "chrome" }, ...],
 * );
 * // report.uncovered: [{ tuple: ["os=mac", "browser=chrome"], ... }]
 */
export function analyzeCoverage(
  parameters: Parameter[],
  tests: TestCase[],
  strength?: number,
): CoverageReport {
  const mod = getModule();
  const result = checkResult<CoverageReport>(mod.analyzeCoverage(parameters, tests, strength ?? 2));
  // When there are no tuples (e.g. fewer parameters than strength), coverage is vacuously 1.0.
  if (result.totalTuples === 0) {
    result.coverageRatio = 1.0;
  }
  return result;
}

/**
 * Extend an existing test suite with additional tests to improve coverage.
 *
 * mode: "strict" (default) keeps existing tests as-is.
 * Only "strict" mode is supported (existing tests are kept as-is).
 */
export function extendTests(existing: TestCase[], input: ExtendInput): GenerateResult {
  const mod = getModule();
  const result = checkResult<GenerateResult>(mod.extendTests(existing, input));
  return result;
}

/**
 * Get model statistics without running generation.
 */
export function estimateModel(input: GenerateInput): ModelStats {
  const mod = getModule();
  const result = checkResult<ModelStats>(mod.estimateModel(input));
  return result;
}
