/**
 * coverwise — Combinatorial test design API.
 *
 * Not just a generation tool — a test design engine.
 * JSON-complete, stateless, decomposable.
 */

// --- Re-exports ---

export type { Condition, ConditionStart, Constraint } from './constraint.js';
export { allOf, anyOf, not, when } from './constraint.js';

// --- Public Types (re-exported from types module) ---

export type {
  BoundaryParameter,
  ClassCoverage,
  CoverageReport,
  CoverwiseErrorCode,
  ExtendInput,
  FloatBoundaryParameter,
  GenerateInput,
  GenerateResult,
  GenerateStats,
  IntegerBoundaryParameter,
  ModelStats,
  Parameter,
  ParameterValue,
  ParamStats,
  PlainParameter,
  SubModel,
  Suggestion,
  TestCase,
  UncoveredTuple,
  WeightConfig,
} from './types.js';
export { CoverwiseError } from './types.js';

import type {
  CoverageReport,
  ExtendInput,
  GenerateInput,
  GenerateResult,
  ModelStats,
  Parameter,
  TestCase,
} from './types.js';
import { CoverwiseError, errorCodeFromNumber } from './types.js';
import {
  validateConstraints,
  validateExtendMode,
  validateGenerateInput,
  validateParameters,
  validateStrength,
  validateTestArray,
} from './validation.js';

// --- WASM Module Loading ---

interface WasmModule {
  generate(input: GenerateInput): GenerateResult | { error: true; code?: number; message?: string };
  analyzeCoverage(
    params: Parameter[],
    tests: TestCase[],
    strength: number,
    constraints?: string[],
  ): CoverageReport | { error: true; code?: number; message?: string };
  extendTests(
    existing: TestCase[],
    input: ExtendInput,
  ): GenerateResult | { error: true; code?: number; message?: string };
  estimateModel(
    input: GenerateInput,
  ): ModelStats | { error: true; code?: number; message?: string };
}

let wasmModule: WasmModule | null = null;
let initPromise: Promise<WasmModule> | null = null;

/**
 * Initialize the WASM module. Must be called before using any API function.
 * Safe to call multiple times — only loads once.
 *
 * @example
 * await init();
 * const result = generate({ parameters: [...] });
 */
export async function init(): Promise<void> {
  if (wasmModule) {
    return;
  }
  if (!initPromise) {
    initPromise = (async () => {
      try {
        // @ts-expect-error — WASM module is generated by `make wasm`, not present at type-check time.
        // Resolves to dist/coverwise.js at runtime (dist/js/../coverwise.js).
        // In vitest, aliased via vitest.config.ts resolve.alias.
        const createModule = await import('../coverwise.js');
        const mod = await createModule.default();
        return mod as WasmModule;
      } catch (e) {
        initPromise = null;
        throw new CoverwiseError(
          'INVALID_INPUT',
          `coverwise WASM module failed to initialize: ${e instanceof Error ? e.message : String(e)}`,
        );
      }
    })();
  }
  wasmModule = await initPromise;
}

function getModule(): WasmModule {
  if (!wasmModule) {
    throw new CoverwiseError(
      'INVALID_INPUT',
      'coverwise WASM module not initialized. Call await init() first.',
    );
  }
  return wasmModule;
}

// --- Input Validation ---

const wasmScalarError = (message: string): Error => new CoverwiseError('INVALID_INPUT', message);

function validateInput(input: GenerateInput): void {
  validateGenerateInput(input, wasmScalarError);
}

// --- Result Checking ---

function checkResult<T>(result: unknown): T {
  const r = result as Record<string, unknown>;
  if (r && r.error === true) {
    // The WASM module reports `code` as the numeric model::Error::Code value.
    const code =
      typeof r.code === 'number'
        ? errorCodeFromNumber(r.code)
        : ((r.code as CoverwiseError['code']) ?? 'INVALID_INPUT');
    throw new CoverwiseError(
      code,
      (r.message as string) ?? 'Unknown error',
      typeof r.detail === 'string' ? r.detail : undefined,
    );
  }
  return result as T;
}

// --- Core API ---

/**
 * Generate a covering array. One function, sensible defaults.
 *
 * @example
 * const result = generate({
 *   parameters: [
 *     { name: "os", values: ["win", "mac", "linux"] },
 *     { name: "browser", values: ["chrome", "firefox", "safari"] },
 *   ],
 * });
 * // result.tests: [{ os: "win", browser: "chrome" }, ...]
 * // result.coverage: 1.0
 */
export function generate(input: GenerateInput): GenerateResult {
  validateInput(input);
  const mod = getModule();
  const result = checkResult<GenerateResult>(mod.generate(input));
  result.negativeTests = result.negativeTests ?? [];
  return result;
}

/**
 * Analyze t-wise coverage of an existing test suite.
 * Use this to check coverage of manually written tests.
 *
 * @example
 * const report = analyzeCoverage(
 *   [{ name: "os", values: ["win", "mac"] }, ...],
 *   [{ os: "win", browser: "chrome" }, ...],
 * );
 * // report.uncovered: [{ tuple: ["os=mac", "browser=chrome"], ... }]
 */
export function analyzeCoverage(
  parameters: Parameter[],
  tests: TestCase[],
  strength?: number,
  constraints?: string[],
): CoverageReport {
  validateParameters(parameters);
  validateTestArray(tests, 'tests');
  validateConstraints(constraints);
  const s = validateStrength(strength, wasmScalarError);
  const mod = getModule();
  const result = checkResult<CoverageReport>(
    mod.analyzeCoverage(parameters, tests, s, constraints ?? []),
  );
  // When there are no tuples (e.g. fewer parameters than strength), coverage is vacuously 1.0.
  if (result.totalTuples === 0) {
    result.coverageRatio = 1.0;
  }
  return result;
}

/**
 * Extend an existing test suite with additional tests to improve coverage.
 *
 * mode: "strict" (default) keeps existing tests as-is.
 * Only "strict" mode is supported (existing tests are kept as-is).
 */
export function extendTests(existing: TestCase[], input: ExtendInput): GenerateResult {
  validateTestArray(existing, 'existing');
  validateInput(input);
  validateExtendMode(input.mode);
  const mod = getModule();
  const result = checkResult<GenerateResult>(mod.extendTests(existing, input));
  result.negativeTests = result.negativeTests ?? [];
  for (let i = 0; i < existing.length; ++i) {
    result.tests[i] = existing[i];
  }
  return result;
}

/**
 * Get model statistics without running generation.
 */
export function estimateModel(input: GenerateInput): ModelStats {
  validateInput(input);
  const mod = getModule();
  const result = checkResult<ModelStats>(mod.estimateModel(input));
  return result;
}

// --- Class-based API ---

/**
 * Class-based wrapper around the coverwise API.
 * Provides the same functionality as the free functions in an object-oriented style.
 *
 * Every method delegates to the corresponding free function so the two styles
 * share a single implementation and cannot drift (validation, existing-test
 * preservation, and error mapping stay identical).
 *
 * @example
 * const cw = await Coverwise.create();
 * const result = cw.generate({ parameters: [...] });
 */
export class Coverwise {
  private constructor() {}

  /**
   * Create a Coverwise instance.
   * Reuses the shared WASM singleton — safe to call multiple times.
   *
   * @example
   * const cw = await Coverwise.create();
   * const result = cw.generate({ parameters: [...] });
   */
  static async create(): Promise<Coverwise> {
    await init();
    return new Coverwise();
  }

  /**
   * Generate a covering array. One function, sensible defaults.
   */
  generate(input: GenerateInput): GenerateResult {
    return generate(input);
  }

  /**
   * Analyze t-wise coverage of an existing test suite.
   */
  analyzeCoverage(
    parameters: Parameter[],
    tests: TestCase[],
    strength?: number,
    constraints?: string[],
  ): CoverageReport {
    return analyzeCoverage(parameters, tests, strength, constraints);
  }

  /**
   * Extend an existing test suite with additional tests to improve coverage.
   */
  extendTests(existing: TestCase[], input: ExtendInput): GenerateResult {
    return extendTests(existing, input);
  }

  /**
   * Get model statistics without running generation.
   */
  estimateModel(input: GenerateInput): ModelStats {
    return estimateModel(input);
  }
}
