/**
 * coverwise — Combinatorial test design API.
 *
 * Not just a generation tool — a test design engine.
 * JSON-complete, stateless, decomposable.
 */

// --- Re-exports ---

export type { Condition, ConditionStart, Constraint, IfConstraint } from './constraint.js';
export { allOf, anyOf, not, when } from './constraint.js';

// --- Public Types (re-exported from types module) ---

export type {
  BoundaryParameter,
  ClassCoverage,
  CoverageReport,
  CoverwiseErrorCode,
  ExtendInput,
  FloatBoundaryParameter,
  GenerateInput,
  GenerateResult,
  GenerateStats,
  IntegerBoundaryParameter,
  ModelStats,
  NegativeCoverage,
  Parameter,
  ParameterValue,
  ParamStats,
  PlainParameter,
  SubModel,
  Suggestion,
  TestCase,
  UncoveredTuple,
  WeightConfig,
} from './types.js';
export { CoverwiseError } from './types.js';

import type {
  CoverageReport,
  ExtendInput,
  GenerateInput,
  GenerateResult,
  ModelStats,
  Parameter,
  TestCase,
} from './types.js';
import { CoverwiseError, errorCodeFromNumber } from './types.js';
import {
  createStringBudget,
  type StringBudget,
  validateConstraints,
  validateExtendMode,
  validateGenerateInput,
  validateParameters,
  validateStrength,
  validateTestArray,
} from './validation.js';

// --- WASM Module Loading ---

interface WasmModule {
  generate(input: GenerateInput): GenerateResult | { error: true; code?: number; message?: string };
  analyzeCoverage(
    params: Parameter[],
    tests: TestCase[],
    strength: number,
    constraints?: string[],
  ): CoverageReport | { error: true; code?: number; message?: string };
  extendTests(
    existing: TestCase[],
    input: ExtendInput,
  ): GenerateResult | { error: true; code?: number; message?: string };
  estimateModel(
    input: GenerateInput,
  ): ModelStats | { error: true; code?: number; message?: string };
}

let wasmModule: WasmModule | null = null;
let initPromise: Promise<WasmModule> | null = null;

/**
 * Initialize the WASM module. Must be called before using any API function.
 * Safe to call multiple times — only loads once.
 *
 * @example
 * await init();
 * const result = generate({ parameters: [...] });
 */
export async function init(): Promise<void> {
  if (wasmModule) {
    return;
  }
  if (!initPromise) {
    initPromise = (async () => {
      try {
        // @ts-expect-error — WASM module is generated by `make wasm`, not present at type-check time.
        // Resolves to dist/coverwise.js at runtime (dist/js/../coverwise.js).
        // In vitest, aliased via vitest.config.ts resolve.alias.
        const createModule = await import('../coverwise.js');
        const mod = await createModule.default();
        return mod as WasmModule;
      } catch (e) {
        initPromise = null;
        throw new CoverwiseError(
          'INVALID_INPUT',
          `coverwise WASM module failed to initialize: ${e instanceof Error ? e.message : String(e)}`,
        );
      }
    })();
  }
  wasmModule = await initPromise;
}

// --- Engine Boundary ---

/**
 * The error a caller sees for a throw this package did not raise.
 *
 * Inspecting the thrown value is itself caller code — the prototype walk behind
 * `instanceof` can hit a proxy trap, `message` may be a getter, and `String`
 * may reach a `toString` that throws — so every step of it is attempted
 * defensively. A step that fails leaves the value unnamed rather than replacing
 * one foreign throw with another.
 */
function asCoverwiseError(thrown: unknown): CoverwiseError {
  try {
    if (thrown instanceof CoverwiseError) {
      return thrown;
    }
  } catch {
    // A value that refuses the prototype walk is not one this package raised.
  }
  let described = 'a value that cannot be described';
  try {
    described = thrown instanceof Error && thrown.message !== '' ? thrown.message : String(thrown);
  } catch {
    // Keep the fallback: describing the value is the caller's code too.
  }
  return new CoverwiseError(
    'INVALID_INPUT',
    `Invalid input: a property read on the input threw (${described}).`,
  );
}

/**
 * Run one call against the engine and let nothing but a {@link CoverwiseError}
 * out of it.
 *
 * Reading a field of a caller-supplied object runs caller code: a getter on a
 * class instance, a reactive ref, a store proxy's trap. Whatever that code
 * throws is a JavaScript exception, so it is not the `std::exception` the
 * compiled module catches and not a `CoverwiseError` this package raised — it
 * would reach the caller as a foreign throw out of a function documented to
 * report failure one way only, from an input as ordinary as a component's
 * state object. Both the validation pass and the engine call read such fields,
 * so both run inside this frame.
 *
 * The module handle is reachable nowhere else: a call that wants the engine has
 * to be written as a body handed to this function, so an entry point added
 * later inherits the conversion instead of having to remember it.
 */
function callEngine<T>(run: (engine: WasmModule) => T): T {
  if (!wasmModule) {
    throw new CoverwiseError(
      'INVALID_INPUT',
      'coverwise WASM module not initialized. Call await init() first.',
    );
  }
  try {
    return run(wasmModule);
  } catch (thrown) {
    throw asCoverwiseError(thrown);
  }
}

// --- Input Validation ---

const wasmScalarError = (message: string): Error => new CoverwiseError('INVALID_INPUT', message);

function validateInput(input: GenerateInput, budget?: StringBudget): void {
  validateGenerateInput(input, wasmScalarError, budget);
}

// --- Result Checking ---

function checkResult<T>(result: unknown): T {
  const r = result as Record<string, unknown>;
  if (r && r.error === true) {
    // The WASM module reports `code` as the numeric model::Error::Code value.
    const code =
      typeof r.code === 'number'
        ? errorCodeFromNumber(r.code)
        : ((r.code as CoverwiseError['code']) ?? 'INVALID_INPUT');
    throw new CoverwiseError(
      code,
      (r.message as string) ?? 'Unknown error',
      // An absent detail is represented as `undefined` on every surface; the
      // WASM module reports it as an empty string, which must not leak through
      // as a distinct value.
      typeof r.detail === 'string' && r.detail !== '' ? r.detail : undefined,
    );
  }
  return result as T;
}

// --- Core API ---

/**
 * Generate a covering array. One function, sensible defaults.
 *
 * @example
 * const result = generate({
 *   parameters: [
 *     { name: "os", values: ["win", "mac", "linux"] },
 *     { name: "browser", values: ["chrome", "firefox", "safari"] },
 *   ],
 * });
 * // result.tests: [{ os: "win", browser: "chrome" }, ...]
 * // result.coverage: 1.0
 */
export function generate(input: GenerateInput): GenerateResult {
  return callEngine((engine) => {
    validateInput(input);
    const result = checkResult<GenerateResult>(engine.generate(input));
    result.negativeTests = result.negativeTests ?? [];
    return result;
  });
}

/**
 * Analyze t-wise coverage of an existing test suite.
 * Use this to check coverage of manually written tests.
 *
 * @example
 * const report = analyzeCoverage(
 *   [{ name: "os", values: ["win", "mac"] }, ...],
 *   [{ os: "win", browser: "chrome" }, ...],
 * );
 * // report.uncovered: [{ tuple: ["os=mac", "browser=chrome"], ... }]
 */
export function analyzeCoverage(
  parameters: Parameter[],
  tests: TestCase[],
  strength?: number,
  constraints?: string[],
): CoverageReport {
  return callEngine((engine) => {
    const budget = createStringBudget();
    validateParameters(parameters, budget);
    validateTestArray(tests, 'tests', budget);
    validateConstraints(constraints, budget);
    const s = validateStrength(strength, wasmScalarError);
    const result = checkResult<CoverageReport>(
      engine.analyzeCoverage(parameters, tests, s, constraints ?? []),
    );
    // An empty tuple universe leaves the ratio undefined; coverage is then
    // vacuously 1.0. Every input that could produce one is turned away earlier:
    // a strength above the parameter count, a parameter with no valid value, and
    // an unsatisfiable constraint model are all rejected before enumeration, and
    // any model that survives them has at least one tuple. This is a guard, not a
    // case with an input to name.
    if (result.totalTuples === 0) {
      result.coverageRatio = 1.0;
    }
    return result;
  });
}

/**
 * Extend an existing test suite with additional tests to improve coverage.
 *
 * mode: "strict" (default) keeps existing tests as-is.
 * Only "strict" mode is supported (existing tests are kept as-is).
 */
export function extendTests(existing: TestCase[], input: ExtendInput): GenerateResult {
  return callEngine((engine) => {
    const budget = createStringBudget();
    validateTestArray(existing, 'existing', budget);
    validateInput(input, budget);
    validateExtendMode(input.mode);
    const result = checkResult<GenerateResult>(engine.extendTests(existing, input));
    result.negativeTests = result.negativeTests ?? [];
    return result;
  });
}

/**
 * Get model statistics without running generation.
 */
export function estimateModel(input: GenerateInput): ModelStats {
  return callEngine((engine) => {
    validateInput(input);
    return checkResult<ModelStats>(engine.estimateModel(input));
  });
}

// --- Class-based API ---

/**
 * Class-based wrapper around the coverwise API.
 * Provides the same functionality as the free functions in an object-oriented style.
 *
 * Every method delegates to the corresponding free function so the two styles
 * share a single implementation and cannot drift (validation, existing-test
 * preservation, and error mapping stay identical).
 *
 * @example
 * const cw = await Coverwise.create();
 * const result = cw.generate({ parameters: [...] });
 */
export class Coverwise {
  private constructor() {}

  /**
   * Create a Coverwise instance.
   * Reuses the shared WASM singleton — safe to call multiple times.
   *
   * @example
   * const cw = await Coverwise.create();
   * const result = cw.generate({ parameters: [...] });
   */
  static async create(): Promise<Coverwise> {
    await init();
    return new Coverwise();
  }

  /**
   * Generate a covering array. One function, sensible defaults.
   */
  generate(input: GenerateInput): GenerateResult {
    return generate(input);
  }

  /**
   * Analyze t-wise coverage of an existing test suite.
   */
  analyzeCoverage(
    parameters: Parameter[],
    tests: TestCase[],
    strength?: number,
    constraints?: string[],
  ): CoverageReport {
    return analyzeCoverage(parameters, tests, strength, constraints);
  }

  /**
   * Extend an existing test suite with additional tests to improve coverage.
   */
  extendTests(existing: TestCase[], input: ExtendInput): GenerateResult {
    return extendTests(existing, input);
  }

  /**
   * Get model statistics without running generation.
   */
  estimateModel(input: GenerateInput): ModelStats {
    return estimateModel(input);
  }
}
